### ISSUE TITLE
Support for an open source solver? 

### ISSUE THREAD

**Issue by nick-youngblut** [vpc-ccg/freddie#36]
Gurobi does not provide free licenses to non-profit research institutes. It would be great if Freddie supported the use of open-source alternatives to the Gurobi Solver (e.g., GLPK or SCIP).

**Comment by baraaorabi** [comment]
Gurobi has free licence for academic institutes. Not sure about other non-profit research institutes.

However, we are soon will be replacing Freddie's code with this repo:
https://github.com/baraaorabi/freddie-sc

The major changes are:
- Much faster and cleaner code
- Rewrote the whole ILP in PuLP which ships with an free and open source solver (COID-OR). If you have another solver installed (CPLEX, Gurobi, etc) with a valid licence, this version of Freddie will detected and you would be able to select it as a command line parameter.

Feel free to start using it now!

**Comment by nick-youngblut** [comment]
> Gurobi has free licence for academic institutes. Not sure about other non-profit research institutes.

We were able to get 1 free license, even though we are not a degree-issuing institute. 

Thanks for the heads up on [freddie-sc](https://github.com/baraaorabi/freddie-sc)!
